-- V4: Inventory Management — add low_stock_threshold to products, create stock_history table

ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS stock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    stock_after INTEGER NOT NULL,
    reference VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_stock_history_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX IF NOT EXISTS idx_stock_history_product ON stock_history(product_id);
